### ISSUE TITLE
ERROR: compilation failed for package ‘Rhisat2’

### ISSUE THREAD

**Issue by bbarthold** [fmicompbio/Rhisat2#2]
I am not sure whether this is just caused by an uncommon mix of circumstances on my end, but `Rhisat2` would not compile on my linux box (R Under development (unstable) (2020-08-10 r79000); Platform: x86_64-pc-linux-gnu (64-bit); Running under: Ubuntu 20.04.1 LTS; BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so). I tried using Bioconductor (v. 3.12), github and installs from several archived versions.

Last lines of the console output were:

```
  In file included from /usr/include/c++/9/bits/locale_conv.h:41,
                   from /usr/include/c++/9/locale:43,
                   from /usr/include/c++/9/iomanip:43,
                   from timer.h:26,
                   from reference.h:36,
                   from splice_site.h:32,
                   from edit.h:30,
                   from splice_site.cpp:20:
  /usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
     53 |   template<typename> class auto_ptr;
        |                            ^~~~~~~~
  splice_site.cpp: In member function ‘void SpliceSiteDB::read(const GFM<unsigned int>&, const EList<ALT<unsigned int> >&)’:
  splice_site.cpp:717:59: warning: ?: using integer constants in boolean context, the expression will always evaluate to ‘true’ [-Wint-in-bool-context]
    717 |             exons.back().init(ref, left, right, fw == '+' ? SPL_FW : SPL_RC);
        |                                                 ~~~~~~~~~~^~~~~~~~~~~~~~~~~
  In file included from edit.h:29,
                   from splice_site.cpp:20:
  ds.h: In instantiation of ‘void EList<T, S>::push_back_array(const T*, size_t) [with T = Exon; int S = 128; size_t = long unsigned int]’:
  splice_site.cpp:722:59:   required from here
  ds.h:663:14: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class Exon’; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
    663 |   std::memcpy(list_ + cur_, l, bytes);
        |   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
  In file included from edit.h:30,
                   from splice_site.cpp:20:
  splice_site.h:377:7: note: ‘class Exon’ declared here
    377 | class Exon {
        |       ^~~~
  ERROR: compilation failed for package ‘Rhisat2’
```

HISAT2, on the other hand, compiled from the recent source without issues.

Throwing the content of src of the current hisat2-2.1.0.source.zip from ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-2.1.0-source.zip into the Rhisat2 src folder from the current https://github.com/fmicompbio/Rhisat2 version (v. 1.5.1), thus replacing all identically named files, including the patched aligner_result.cpp, fixed the issue for me.

**Comment by csoneson** [comment]
Thanks for the report! We'll have to look into this (it seems to build fine on the Ubuntu 20.04.1 LTS [Bioc builder](http://bioconductor.org/checkResults/3.12/bioc-LATEST/Rhisat2/nebbiolo1-install.html), the same last lines of output, but no error).

**Comment by csoneson** [comment]
I'm still not sure what's going on here...I added an additional platform to the [GitHub actions builds](https://github.com/fmicompbio/Rhisat2/runs/1026803389?check_suite_focus=true), trying to replicate your setup as closely as possible (see ubuntu-20.04 (devel - devel - )), but v1.5.1 still installs fine...the only difference I can see is the BLAS - the GHA builder is using the default R BLAS (se the Session info in the link above) while you have OpenBLAS.

**Comment by csoneson** [comment]
Another possibility - could it be a difference in the compile flags (h/t @mbstadler)? Bioconductor lists the compile flags for the ubuntu 20.04 machine [here](http://bioconductor.org/checkResults/3.12/bioc-LATEST/nebbiolo1-NodeInfo.html). I've also included the compiler version/flags in the GitHub actions output linked above (check under the 'Print compiler flags' step). Could you check if there are any differences to your setup?

**Comment by csoneson** [comment]
I will close this issue for now since it's not clear that there is a general problem with `Rhisat2`. Feel free to reopen if there are additional comments.

**Comment by tom91136** [comment]
To provide some closure, I got very similar looking warnings in my build, but if I inspect the log, I can eventually see:
```
* installing to library ‘/root/tmp/libdir’
* installing *source* package ‘Rhisat2’ ...
** using staged installation
** libs
/usr/bin/g++ -O3   -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3   -funroll-loops -g3 -std=c++11\"" -std=c++11 \
-fno-strict-aliasing -DHISAT2_VERSION="\"2.2.1\"" -DBUILD_HOST="\"707214f512f8\"" -DBUILD_TIME="\"Sun May 26 08:53:31 UTC 2024\"" -DCOMPILER_VERSION="\"`/usr/bin/g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DUSESIMDE -DBOWTIE2 -DNDEBUG -Wall -DMASSIVE_DATA_RLCSA \
-I. -I third_party \
-o hisat2-build-s hisat2_build.cpp \
ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp gfm.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp tinythread.cpp diff_sample.cpp hisat2_build_main.cpp \
-lpthread 
/usr/bin/g++ -O3   -funroll-loops -g3 -DCOMPILER_OPTIONS="\"-O3   -funroll-loops -g3 -std=c++11\"" -std=c++11 \
-fno-strict-aliasing -DHISAT2_VERSION="\"2.2.1\"" -DBUILD_HOST="\"707214f512f8\"" -DBUILD_TIME="\"Sun May 26 08:53:31 UTC 2024\"" -DCOMPILER_VERSION="\"`/usr/bin/g++ -v 2>&1 | tail -1`\"" -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DBOWTIE_MM  -DUSESIMDE  -DBOWTIE2 -DNDEBUG -Wall \
-I. -I third_party  \
-o hisat2-align-s hisat2.cpp \
ccnt_lut.cpp ref_read.cpp alphabet.cpp shmem.cpp edit.cpp gfm.cpp reference.cpp ds.cpp multikey_qsort.cpp limit.cpp random_source.cpp tinythread.cpp qual.cpp pat.cpp read_qseq.cpp aligner_seed_policy.cpp aligner_seed.cpp aligner_seed2.cpp aligner_sw.cpp aligner_sw_driver.cpp aligner_cache.cpp aligner_result.cpp ref_coord.cpp mask.cpp pe.cpp aln_sink.cpp dp_framer.cpp scoring.cpp presets.cpp unique.cpp simple_func.cpp random_util.cpp aligner_bt.cpp sse_util.cpp aligner_swsse.cpp outq.cpp aligner_swsse_loc_i16.cpp aligner_swsse_ee_i16.cpp aligner_swsse_loc_u8.cpp aligner_swsse_ee_u8.cpp aligner_driver.cpp splice_site.cpp hisat2_main.cpp \
-lpthread  
mkdir -p ../inst
cp hisat2-align-s ../inst/hisat2
cp: cannot stat 'hisat2-align-s': No such file or directory
make: *** [Makefile:578: ../inst/hisat2] Error 1
make: *** Waiting for unfinished jobs....
# Similar looking compiler warnings....
```

This failure is a bit hard to recreate but I suspect if you run a parallel build (set `MAKEFLAGS=j4`) then there's a race condition with some of the dependent files. 
This might be caused by underspecified make rules, etc.
